# Generated by Django 3.2.5 on 2021-07-11 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facilityid', models.AutoField(db_column='FacilityID', primary_key=True, serialize=False)),
                ('facilityname', models.CharField(db_column='FacilityName', max_length=100)),
                ('managementfactor', models.FloatField(db_column='ManagementFactor')),
                ('create', models.DateTimeField(db_column='Created', default=datetime.datetime(2021, 7, 11, 19, 51, 48, 657183))),
                ('time', models.DateTimeField(db_column='Time', default=datetime.datetime(2021, 7, 11, 19, 51, 48, 657183))),
                ('siteid', models.ForeignKey(db_column='SiteID', on_delete=django.db.models.deletion.CASCADE, to='siteApp.sites')),
            ],
            options={
                'db_table': 'facility',
                'ordering': ('facilityid',),
                'managed': True,
            },
        ),
    ]
