# Generated by Django 3.2.5 on 2021-07-11 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210711_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 19, 51, 48, 661185)),
        ),
    ]
